name: colorization-pytorch

channels:
    - default
    - pytorch

dependencies:
    - python >= 3.6
    - cudatoolkit = 9.0
    - matplotlib
    - numpy
    - pytorch-nightly
    - scikit-image
    - torchvision
