name: colorization-pytorch

channels:
    - default
    - lukepfister
    - pytorch

dependencies:
    - python >= 3.6
    - caffe-gpu
    - cudatoolkit = 9.0
    - matplotlib
    - numpy
    - psutil
    - pycuda
    - pytorch-nightly
    - scikit-image
    - torchvision
